title: "NUSSU commIT Championship"
theme: jekyll-theme-slate

header_pages:
  - Overview.md
  - Challenge.md
  - Submission.md

markdown: kramdown

repository: "luciatirta/commit-championship"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
